### ISSUE TITLE
Underlying architecture of the System 

### ISSUE THREAD

**Issue by jeffreypeter** [airavata-courses/SinghPrasandeep#1]
Hi,

Could you share the underlying architecture diagram of your system?

**Comment by jeffreypeter** [comment]
I am trying to understand how the containers are talking to each other

**Comment by singhPrasan** [comment]
@jeffreypeter The microservices are independent as of now and they do not interact with each other. I'll be adding a User Interface to the application tonight for easy access to the three containers.

**Comment by singhPrasan** [comment]
@jeffreypeter Added a project Wiki to highlight project architecture and updated build instructions. Also, I have removed Docker for now, so you might need to run the project again and install some dependencies. This was earlier taken care of by the Docker container.
Please raise an issue if you are not able to run the application

**Comment by jeffreypeter** [comment]
I was able to run the application.
