### ISSUE TITLE
Communication between microservices

### ISSUE THREAD

**Issue by sachinkariyattin** [airavata-courses/SinghPrasandeep#3]
@SinghPrasandeep 
I was able to call all the microservices and get the output based on the ReadMe instructions!!

However, I would like to suggest the following enhancements.
 * Use the  [Apache HTTP client ](https://www.mkyong.com/webservices/jax-rs/restful-java-client-with-apache-httpclient/) in java or the [requests](http://docs.python-requests.org/en/master/) module in python to send messages between both the services
 * Also, currently the UI is not being run on any server instance. You can run your `index.html` on a simple node.js http server instance. Here is an example [(example)](https://stackoverflow.com/questions/6084360/using-node-js-as-a-simple-web-server)

**Comment by singhPrasan** [comment]
@sachinkariyattin Added a python server for user interface to run. It now runs on localhost:8000 (check readMe). Will be adding inter-communication amongst microservices soon

**Comment by singhPrasan** [comment]
@sachinkariyattin implemented inter-connectivity between microservices and added a project Wiki. Also, I have removed Docker for now, so you might need to run the project again and install some dependencies. This was earlier taken care of by the Docker container.
Please raise an issue if you are not able to run the application

**Comment by sachinkariyattin** [comment]
I was able to run it
